name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem are you trying to solve? What use case does this address?
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: edition
    attributes:
      label: Which edition would this feature belong to?
      description: See CONTRIBUTING.md for CE vs EE guidelines
      options:
        - Community Edition (core ADR features)
        - Enterprise Edition (integrations, AI, etc.)
        - Not sure
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots about the feature request.
